name: rutas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.1.2 
  #Persistir ruta activa
  shared_preferences: ^2.3.2

  #Permisos
  permission_handler: ^12.0.1

  # Networking
  http: ^1.2.2

  # Geocoding (dirección -> lat/lon). Mantén UNA versión.
  geocoding: ^4.0.0

  # GPS del dispositivo (opcional; si no lo usas, puedes quitarlo)
  geolocator: ^14.0.2

  # Mapas OSM
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Utils / almacenamiento local (si los usas)
  sqflite: ^2.4.2
  path: ^1.9.1

  # UI
  cupertino_icons: ^1.0.8

  # Tareas en segundo plano
  flutter_foreground_task: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1B3C53"
  adaptive_icon_foreground: "assets/images/logo.png"
